services:
  # Backend Service
  - type: web
    name: medical-image-backend
    env: python
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      python manage.py seed_data --count 20
      python create_production_superuser.py
    startCommand: gunicorn medproject.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: medical-image-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://medical-image-frontend.onrender.com
      - key: ADMIN_USERNAME
        value: medadmin
      - key: ADMIN_EMAIL
        value: admin@medicalimagesearch.com
      - key: ADMIN_PASSWORD
        generateValue: true

  # Frontend Service  
  - type: web
    name: medical-image-frontend
    env: node
    region: oregon
    rootDir: frontend
    buildCommand: |
      npm ci
      npm run build
    startCommand: npx serve -s build -l 10000
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: REACT_APP_API_URL
        value: https://medical-image-backend.onrender.com 