services:
  - type: web
    name: medical-image-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn medproject.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: medical-image-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.vercel.app 